apiVersion: sync.secrets-bridge.io/v1alpha1
kind: SecretsSync
metadata:
  labels:
    app.kubernetes.io/name: secrets-bridge
    app.kubernetes.io/managed-by: kustomize
  name: secretssync-sample
spec:
  # TODO(user): Add fields here
